# Config Server
server:
  address: localhost
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1
        min-idle: 0
    database: 0

# Mybatis-Plus Config http://mp.baomidou.com/#/spring-boot
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.zwl.mall.entity
  global-config:
    id-type: 2
    field-strategy: 0
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

#pagehelper分页插件配置
pagehelper:
  helperDialect: postgresql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
