# Config Server
server:
  address: localhost
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      write:
        url: jdbc:mysql://47.98.55.127:3306/mall_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: weigu2018
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      read:
        url: jdbc:mysql://47.98.55.127:3306/mall_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: weigu2018
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      read-key: get,select,count,list,query,find
      write-key: add,create,update,delete,remove,insert
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1
        min-idle: 0
    database: 0

# Mybatis-Plus Config http://mp.baomidou.com/#/spring-boot
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.zwl.mall.entity
  global-config:
    id-type: 2
    field-strategy: 0
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    jdbcTypeForNull: null
    multipleResultSetsEnabled: true

