GET http://ersx.com.cn/api/pub/authorize?returnUrl=http://ersx.com.cn
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8


> {% client.global.set("token", response.body.AccessToken.token); %}


###

