GET {{host}}/api/pub/authorize?returnUrl=kj.yizhidao9.com
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8


> {% client.global.set("token", response.body.AccessToken.token); %}


###

