GET http://localhost:8080/api/pub/loginWithPhoneCode?cellphone=17682333183&code=123
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8


> {% client.global.set("token", response.body.data); %}

###

