POST {{host}}/api/out/user_account/info
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8


{ "phone":"13000000000", "mid":"kj", "access_token":"27e830ffbe484a4181e7d02b9e2f0750" }


###

