GET http://localhost:8080/api/user/energy/consume?hours=1
Accept: */*
Cache-Control: no-cache
Authorization: {{token}}
###

GET http://localhost:8080/api/user/energy/add?type=1
Accept: */*
Cache-Control: no-cache
Authorization: {{token}}
###

