GET {{host}}/api/user/task/info
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Authorization: {{token}}

###

GET {{host}}/api/user/user_account/info
Accept: */*
Cache-Control: no-cache
Authorization: {{token}}
Content-Type: application/json


###

GET {{host}}/api/user/task/complete?type=2
Accept: */*
Cache-Control: no-cache
Authorization: {{token}}
Content-Type: application/json

###

GET {{host}}/api/user/energy/consume?hours=1
Accept: */*
Cache-Control: no-cache
Authorization: {{token}}
###


