GET http://localhost:8080/api/user/task/info
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Authorization: {{token}}

###

GET {{host}}/api/user/user_account/info
Accept: */*
Cache-Control: no-cache
Authorization: {{token}}
Content-Type: application/json

